/*
 * Copyright 2007-2011 Tom Castle & Lawrence Beadle
 * Licensed under GNU Lesser General Public License
 * 
 * This file is part of EpochX: genetic programming software for research
 * 
 * EpochX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * EpochX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with EpochX. If not, see <http://www.gnu.org/licenses/>.
 * 
 * The latest version is available from: http://www.epochx.org
 */
package org.epochx.ge.init;

import static org.epochx.Population.SIZE;
import static org.epochx.ge.Chromosome.MAXIMUM_LENGTH;

import java.util.*;

import org.epochx.*;
import org.epochx.event.*;
import org.epochx.fitness.FitnessEvaluator;
import org.epochx.ge.*;
import org.epochx.grammar.*;

/**
 * Initialisation implementation which constructs each program's chromosome
 * while ensuring that it maps to a full parse tree of the specified depth.
 * While all programs generated with this initialiser will have a parse tree
 * of the same depth, the length of the resulting chromosome may vary as
 * different paths through the grammar may require different amounts of
 * production choices. Each codon is generated by randomly choosing a value up
 * to the maximum codon value, which will provide the necessary production
 * choice to construct the full parse tree.
 * 
 * <p>
 * Since the initialisation is tied to the parse tree, it uses an internal
 * mapping which is equivalent to the <code>DepthFirstMapper</code>. This is not
 * currently changeable.
 * 
 * <p>
 * If a model is provided then the following parameters are loaded upon every
 * configure event:
 * 
 * <ul>
 * <li>population size</li>
 * <li>random number generator</li>
 * <li>grammar</li>
 * <li>maximum initial depth</li>
 * <li>maximum codon value</li>
 * </ul>
 * 
 * <p>
 * If the <code>getModel</code> method returns <code>null</code> then no model
 * is set and whatever static parameters have been set as parameters to the
 * constructor or using the standard accessor methods will be used. If any
 * compulsory parameters remain unset when the initialiser is requested to
 * generate new programs, then an <code>IllegalStateException</code> will be
 * thrown.
 * 
 * @see FixedLengthInitialisation
 * @see GrowInitialiser
 * @see RampedHalfAndHalfInitialiser
 */
public class FullInitialisation implements GEInitialisation, Listener<ConfigEvent> {

	// Configuration settings
	private RandomSequence random;
	private Grammar grammar;
	private int populationSize;
	private int depth;
	private int maxCodonValue;
	private boolean allowDuplicates;

	/**
	 * Constructs a <tt>FullInitialisation</tt> with control parameters
	 * automatically loaded from the config
	 */
	public FullInitialisation() {
		this(true);
	}

	/**
	 * Constructs a <tt>FullInitialisation</tt> with control parameters
	 * initially loaded from the config. If the <tt>autoConfig</tt> argument is
	 * set to <tt>true</tt> then the configuration will be automatically updated
	 * when the config is modified.
	 * 
	 * @param autoConfig whether this operator should automatically update its
	 *        configuration settings from the config
	 */
	public FullInitialisation(boolean autoConfig) {
		setup();

		if (autoConfig) {
			EventManager.getInstance().add(ConfigEvent.class, this);
		}
	}

	/**
	 * Sets up this operator with the appropriate configuration settings.
	 * This method is called whenever a <tt>ConfigEvent</tt> occurs for a
	 * change in any of the following configuration parameters:
	 * <ul>
	 * <li>{@link Population#SIZE}
	 * <li>{@link STGPIndividual#MAXIMUM_LENGTH}
	 * <li>{@link InitialisationMethod#ALLOW_DUPLICATES} (default: <tt>true</tt>)
	 * </ul>
	 */
	protected void setup() {
		//populationSize = Config.getInstance().get(SIZE);
		allowDuplicates = Config.getInstance().get(ALLOW_DUPLICATES, true);
		//chromosomeLength = Config.getInstance().get(MAXIMUM_LENGTH);
	}

	/**
	 * Receives configuration events and triggers this operator to reconfigure
	 * if the <tt>ConfigEvent</tt> is for one of its required parameters
	 * 
	 * @param event {@inheritDoc}
	 */
	@Override
	public void onEvent(ConfigEvent event) {
		if (event.isKindOf(SIZE, ALLOW_DUPLICATES)) {
			setup();
		}
	}
	
	/**
	 * Creates a population of new <tt>GEIndividuals</tt>. Each individual is 
	 * created by a call to the<tt>createIndividual</tt> method. The size of the
	 * population will be equal to the {@link Population#SIZE} config parameter.
	 * If the {@link InitialisationMethod#ALLOW_DUPLICATES} config parameter is 
	 * set to <tt>false</tt> then the individuals in the population will be 
	 * unique according to their <tt>equals</tt> methods. By default, duplicates
	 * are allowed.
	 * 
	 * @return a population of <tt>GEIndividual</tt> objects
	 */
	@Override
	public Population createPopulation() {
		EventManager.getInstance().fire(new InitialisationEvent.StartInitialisation());
		
		Population population = new Population();

		for (int i = 0; i < populationSize; i++) {
			GEIndividual individual;
			do {
				individual = createIndividual();
			} while (!allowDuplicates && population.contains(individual));

			population.add(individual);
		}
		
		EventManager.getInstance().fire(new InitialisationEvent.EndInitialisation(population));

		return population;
	}

	/**
	 * Constructs a new <code>GEIndividual</code> with a sequence of
	 * codons that map to a full derivation tree on the currently set grammar.
	 * 
	 * @return a new <code>GEIndividual</code> instance.
	 */
	@Override
	public GEIndividual createIndividual() {
		if (grammar == null) {
			throw new IllegalStateException("no grammar has been set");
		}

		GrammarRule start = grammar.getStartRule();

		// Determine the minimum depth possible for a valid program.
		int minDepth = start.getMinDepth();
		if (minDepth > depth) {
			throw new IllegalStateException("no possible programs within given max depth parameter for this grammar");
		}

		// Empty list of codons to be filled.
		final List<Integer> codons = new ArrayList<Integer>();

		// Fill in the list of codons with reference to the grammar.
		fillCodons(codons, start, 0, depth);
		
		ChromosomeOld chromosomeOld = new ChromosomeOld(codonGenerator, codons);

		return new GEIndividual(chromosomeOld);
	}

	/*
	 * Constructs a full parse tree by making appropriate production choices
	 * and then filling in a randomly selected codon that matches the production
	 * choice.
	 */
	private void fillCodons(final List<Integer> codons, final GrammarNode rule, final int currentDepth,
			final int maxDepth) {

		if (rule instanceof GrammarRule) {
			final GrammarRule nt = (GrammarRule) rule;

			// Check if theres more than one production.
			int productionIndex = 0;
			final int noProductions = nt.getNoProductions();
			if (noProductions > 1) {
				final List<Integer> validProductions = getValidProductionIndexes(nt.getProductions(), maxDepth
						- currentDepth
						- 1);

				// Choose a production randomly.
				final int chosenProduction = rng.nextInt(validProductions.size());
				productionIndex = validProductions.get(chosenProduction);

				// Scale the production index up to get our new codon.
				final int codon = convertToCodon(productionIndex, noProductions);

				codons.add(codon);
			}

			// Drop down the tree at this production.
			final GrammarProduction p = nt.getProduction(productionIndex);

			final List<GrammarNode> symbols = p.getGrammarNodes();
			for (final GrammarNode s: symbols) {
				fillCodons(codons, s, currentDepth + 1, maxDepth);
			}
		}
	}

	/*
	 * Helper method for fillCodons which determines which of a set of
	 * productions are valid choices to meet the depth constraints.
	 */
	private List<Integer> getValidProductionIndexes(final List<GrammarProduction> grammarProductions, final int maxDepth) {
		final List<Integer> validRecursive = new ArrayList<Integer>();
		final List<Integer> validAll = new ArrayList<Integer>();

		for (int i = 0; i < grammarProductions.size(); i++) {
			final GrammarProduction p = grammarProductions.get(i);

			if (p.getMinDepth() <= maxDepth) {
				validAll.add(i);

				if (p.isRecursive()) {
					validRecursive.add(i);
				}
			}
		}

		// If there were any valid recursive productions, return them, otherwise
		// use the others.
		return validRecursive.isEmpty() ? validAll : validRecursive;
	}

	/*
	 * Converts a production choice from a number of productions to a codon by
	 * scaling the production index up to a random number inside the model's
	 * max codon size limit, while maintaining the modulo of the number.
	 */
	private int convertToCodon(final int productionIndex, final int noProductions) {
		if (maxCodonValue < 3) {
			throw new IllegalStateException("maximum codon value cannot be less than 3");
		}

		int codon = rng.nextInt(maxCodonValue - noProductions);

		// Increment codon until it is valid index.
		int currentIndex = codon % noProductions;
		// Comparing separate index count saves us %ing large ints.
		while ((currentIndex % noProductions) != productionIndex) {
			codon++;
			currentIndex++;
		}

		return codon;
	}

	/**
	 * Returns whether or not duplicates are currently accepted or rejected from
	 * generated populations.
	 * 
	 * @return <code>true</code> if duplicates are currently accepted in any
	 *         populations generated by the <code>getInitialPopulation</code>
	 *         method and <code>false</code> otherwise
	 */
	public boolean isDuplicatesEnabled() {
		return allowDuplicates;
	}

	/**
	 * Sets whether duplicates should be allowed in the populations that are
	 * generated, or if they should be discarded.
	 * 
	 * @param allowDuplicates whether duplicates should be accepted in the
	 *        populations that are constructed.
	 */
	public void setDuplicatesEnabled(final boolean acceptDuplicates) {
		this.allowDuplicates = acceptDuplicates;
	}

	/**
	 * Returns the random number generator that this initialiser is using or
	 * <code>null</code> if none has been set.
	 * 
	 * @return the rng the currently set random number generator.
	 */
	public RandomNumberGenerator getRNG() {
		return rng;
	}

	/**
	 * Sets the random number generator to use. If a model has been set then
	 * this parameter will be overwritten with the random number generator from
	 * that model on the next configure event.
	 * 
	 * @param rng the random number generator to set.
	 */
	public void setRNG(final RandomNumberGenerator rng) {
		this.rng = rng;
	}

	/**
	 * Returns the grammar that this initialiser is generating programs to
	 * satisfy. It is using this grammar that the initialiser will choose codons
	 * that form full parse trees.
	 * 
	 * @return the grammar that generated programs are being constructed for.
	 */
	public Grammar getGrammar() {
		return grammar;
	}

	/**
	 * Sets the grammar that should be used to determine which codons to use to
	 * create a full program parse tree.
	 * 
	 * @param grammar the <code>Grammar</code> that generated programs should be
	 *        constructed for.
	 */
	public void setGrammar(final Grammar grammar) {
		this.grammar = grammar;
	}

	/**
	 * Returns the size of the populations that this initialiser constructs or
	 * <code>-1</code> if none has been set.
	 * 
	 * @return the size of the populations that this initialiser will generate.
	 */
	public int getPopulationSize() {
		return populationSize;
	}

	/**
	 * Sets the size of the populations that this initialiser should construct
	 * on calls to the <code>getInitialPopulation</code> method.
	 * 
	 * @param populationSize the size of the populations that should be created by this
	 *        initialiser.
	 */
	public void setPopulationSize(final int popSize) {
		this.populationSize = popSize;
	}

	/**
	 * Returns the depth that every parse tree generated by this initialiser
	 * should have.
	 * 
	 * @return the depth of the parse trees constructed.
	 */
	public int getDepth() {
		return depth;
	}

	/**
	 * Sets the depth that the parse trees this initialiser constructs should
	 * be.
	 * 
	 * @param depth the depth of all new parse trees.
	 */
	public void setDepth(final int depth) {
		this.depth = depth;
	}

	/**
	 * Returns the maximum value that codons chosen by this initialiser are
	 * allowed to have.
	 * 
	 * @return the maxCodonValue the maximum integer value that codons selected
	 *         by this initialiser may take.
	 */
	public int getMaximimCodonValue() {
		return maxCodonValue;
	}

	/**
	 * Sets the maximum value that codons chosen by this initialiser should
	 * take.
	 * 
	 * @param maxCodonValue the maximum integer value that codons selected by
	 *        this initialiser should take.
	 */
	public void setMaximumCodonValue(int maxCodonValue) {
		this.maxCodonValue = maxCodonValue;
	}
}
